const translations = {
    en: {
        startGame: "Start Game",
        exitGame: "Exit Game",
        shipPlacement: "SHIP PLACEMENT",
        firstPlayerPrompt: "First player get ready.\nPlayer two look away",
        secondPlayerPrompt: "Second player get ready.\nPlayer one look away",
        consoleTooSmall: "Console size too small. Please resize to at least {width}x{height} and restart the game.",
        units: {
            carrier: "Carrier",
            battleship: "Battleship",
            cruiser: "Cruiser",
            submarine: "Submarine",
            destroyer: "Destroyer",
        
        },
        shipPlacement: "Ship Placement Phase",
        controls: "Controls",
        arrowKeys: "Arrow keys",
        moveCursor: "Move cursor",
        rotateKey: "R",
        rotateShip: "Rotate ship",
        enterKey: "Enter",
        placeShip: "Place ship",
        shipsToPlace: "Ships to place",
        spaces: "spaces",
    },
    no: {
        startGame: "Start spillet",
        exitGame: "Avslutt spillet",
        shipPlacement: "SKIPPLASSERING",
        firstPlayerPrompt: "Første spiller gjør deg klar.\nAndre spiller, se bort",
        secondPlayerPrompt: "Andre spiller gjør deg klar.\nFørste spiller, se bort",
        consoleTooSmall: "Konsollen er for liten. Endre størrelsen til minst {width}x{height} og prøv igjen.",
        units: {
            carrier: "Hangarskip",
            battleship: "Slagskip",
            cruiser: "Krysser",
            submarine: "Ubåt",
            destroyer: "Destroyer",
        },
        shipPlacement: "Plasseringsfase for skip",
        controls: "Kontroller",
        arrowKeys: "Piltaster",
        moveCursor: "Flytt markør",
        rotateKey: "R",
        rotateShip: "Roter skip",
        enterKey: "Enter",
        placeShip: "Plasser skip",
        shipsToPlace: "Skip som skal plasseres",
        spaces: "plasser",
    },
};

export default translations;
